version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: telecomm_sim
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: telecomm_sim
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 15s
      retries: 10
    ports:
          - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - telecomm-network

  backend:
    build:
      context: ./telecomm-sim-back
      dockerfile: Dockerfile
    container_name: telecomm-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://telecomm_sim:3306/telecomm_sim
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - telecomm-network

volumes:
  mysql-data:

networks:
  telecomm-network:
